framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
            rabbit:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 20
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                options:
                    exchange:
                        name: main
                        type: direct
                    queues:
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async