volumes:
  app_volume:
    name: ${APP_NAME}-volume
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,wsize=32768,rsize=32768
      device: ":${PWD}"

services:
  db:
    container_name: ${APP_NAME}-db
    build:
      context: db
      args:
        MYSQL_USER: ${DB_USER}
        MYSQL_DATABASE: ${DB_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_START_TIMEOUT: 900
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql

  php:
    container_name: ${APP_NAME}-php
    build:
      context: php-fpm
      args:
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        PROJECT_TIMEZONE: ${PROJECT_TIMEZONE}
    working_dir: /app
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - app_volume:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    ports:
      - "9000:9000"

  nginx:
    container_name: ${APP_NAME}-nginx
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./.data/nginx/logs:/var/log/nginx
      - app_volume:/app

  clickhouse:
    container_name: ${APP_NAME}-clickhouse
    image: clickhouse/clickhouse-server:24.7.3.42
    restart: always
    volumes:
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_MANUAL_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_MANUAL_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123"

  rabbitmq:
    hostname: 'dev-rabbitmq'
    container_name: ${APP_NAME}-rabbitmq
    build:
      context: ./..
      dockerfile: docker/rabbitmq/Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq:rw
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    container_name: ${APP_NAME}-redis
    image: redis
    volumes:
      - ./.data/redis/data:/data
    ports:
      - "6379:6379"
